version: "3.2"
services:
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      -  portainer_data:/data
  deepstream:
    image: deepstreamio/deepstream.io
    ports:
      - "6020:6020"
      - "6021:6021"
    volumes:
      - ./conf:/etc/deepstream

volumes:
  portainer_data:
